test:
	@../test.pl -e -p -c 'sh ../chain.sh \
	   ../../../src/goto-analyzer/goto-analyzer \
	   ../../../src/goto-cc/goto-cc \
	   ../../../src/goto-instrument/goto-instrument \
	   ../../../src/cbmc/cbmc'